[build]
builder = "NIXPACKS"

[start]
cmd = "python3 bot.py"

[phases.setup]
nixPkgs = ["python312", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]
