[build]
builder = "NIXPACKS"

[start]
cmd = "python bot.py"

[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]
